name: Radon Cyclomatic Complexity

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  radon-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install radon

    - name: Run Radon Cyclomatic Complexity
      id: radon
      run: |
        radon_output=$(radon cc -s -a src/)
        echo "$radon_output"
        echo "::set-output name=radon_output::$radon_output"

    - name: Comment on Pull Request
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: Radon Cyclomatic Complexity Report
        message: |
          ```console
          ${{ steps.radon.outputs.radon_output }}
          ```