name: Radon Analysis

on:
  pull_request:
    paths:
      - '**/*.py' # Only trigger for Python files

jobs:
  radon_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Radon
      run: pip install radon

    - name: Get list of changed files
      id: get_changed_files
      run: |
        echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '.py$')" >> $GITHUB_ENV

    - name: Run Radon analysis
      id: radon_analysis
      run: |
        if [ -z "${{ env.CHANGED_FILES }}" ]; then
          echo "No Python files changed."
          echo "RESULTS=None" >> $GITHUB_ENV
        else
          RESULTS=$(echo "${{ env.CHANGED_FILES }}" | xargs radon cc -s -n A)
          echo "RESULTS=$RESULTS" >> $GITHUB_ENV
        fi

    - name: Comment on PR
      if: env.RESULTS != 'None'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: Radon Complexity Analysis
        message: |
          **Radon Analysis Results:**
          ```
          ${{ env.RESULTS }}
          ```

    - name: Comment no Python files found
      if: env.RESULTS == 'None'
      run: echo "No Python files changed in this PR."
