name: Radon Analysis
on:
  pull_request:
    branches: ["2.0"]

jobs:
  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Radon
        run: pip install radon
      - name: Create Radon's reports
        run: |
          radon cc $(git diff --name-only 2.0) -j >cc.json
          radon mi $(git diff --name-only 2.0) -j >mi.json
          radon hal $(git diff --name-only 2.0) -j >hal.json
      - name: Comment the results on the PR
        uses: Libra-foundation/radon-comment@v0.1
        with:
          cc: "cc.json"
          mi: "mi.json"
          hal: "hal.json"